
#include "clock.h"


void system_clockInit()
{
	/*************>>>>>>> STEPS TO BE FOLLOWED <<<<<<<<************
	
	1. ENABLE HSE and wait for the HSE/HSI to become Ready
	2. Set the POWER ENABLE CLOCK and VOLTAGE REGULATOR (OPTIONAL)
	3. Configure the FLASH PREFETCH and the LATENCY Related Settings
	4. Configure the PRESCALARS HCLK, PCLK1, PCLK2
	5. Configure the MAIN PLL
	6. Enable the PLL and wait for it to become ready
	7. Select the Clock Source and wait for it to be set
	
	********************************************************/
	
	// HSE CLOCK IS SELECTED
	RCC->CR |= RCC_CR_HSEON;   // (1<<16)

	// WAITING TILL HSE IS READY OR NOT UNDER A WHILE LOOP
	while(!(RCC->CR & RCC_CR_HSERDY))		//CHECK (1<<27) IS 1												
	{}
	// FLASH TO BE SET ACCORDING TO THE HAL DOCUMENTATIOIN AND BUFFER SETTING	
	FLASH -> ACR |= FLASH_ACR_LATENCY_1  | FLASH_ACR_PRFTBE;	
	
	// INITLAISE THE PLL SOURCE FIRST - HSE OR HSI [PLLSRC]
	// INITIALISE THE PLL INITIAL INPUT DIVIDER [PLLXTPRE]
		
	RCC->CFGR |= (1<<16);        							// INITLAISE AS HSE [PLLSRC] OR USED RCC_CFGR_PLLSRC 
  RCC->CFGR |= RCC_CFGR_PLLXTPRE_HSE;				// INITLIASE NO DIVIDER [PLLXTPRE]
	RCC->CFGR |= RCC_CFGR_PLLMULL2 ;					// NEXT BLOCK IS PLL MULTIPLICATION BLOCK MY CONDITION IS MLTIPLICATION FACTOR 2.
	
	/* INITIALISE THE AHB ABP1 APB2 BUS PRESCALER THAT IS DONE BY SETTING THE PPRE2,PPRE1,HPRE REGISTERS  */

	               // PPRE1 REG         // PPRE2 REG             // HPRE REG
	RCC->CFGR |= 	(RCC_CFGR_PPRE1_DIV1 | RCC_CFGR_PPRE2_DIV1 | RCC_CFGR_HPRE_DIV1);
	
	// TURN ON THE PLL SOURCE FROM CR REGISTER
	
	RCC-> CR |= (1<<24);        // ORWE CAN USE ~RCC_CR_PLLON~ 
		
	// CHECK THE CONDTION TILL PLL IS ON USING WHILE
	while(!(RCC->CR & RCC_CR_PLLRDY))
	{}
	// INITLIASING THE CLOCK OUTPUT USING THE MCO REGISTER// 
	RCC->CFGR |=   RCC_CFGR_MCO_PLL;   //SAME AS ((1<<26)|(1<<25)|(1<<24));  // INITIALISING PLL AS CLOCK SOURCE INITILAISED BY THE MUX STEP
	
	RCC->CFGR |= RCC_CFGR_SW_PLL;
	while(!(RCC->CFGR & RCC_CFGR_SWS_PLL))
	
  {}

}


